# Generated by Django 3.2.12 on 2022-02-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='furigana',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
