# Generated by Django 3.2.12 on 2022-02-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_furigana'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='chosya',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
